name: Auto Deploy Development

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: centos:7

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: executing remote ssh commands using password
        uses: ./
        with:
            host: 38.47.67.12
            username: doniderawski
            password: Donider123!@#
            script: echo "Test"